name = "samurai-worker"
main = "worker.js"
compatibility_date = "2023-10-01"

# في التطوير تقدر تستعمل workers_dev = true
workers_dev = true

[vars]
# هنا كيتحدد عنوان السرفر الحقيقي اللي فيه Flask
# في حالتك الآن محلي:
SAMURAI_LOCAL_SERVER = "http://127.0.0.1:5000/collect"
