name = "samurai-captcha-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

# أقل شيء خاص Cloudflare Worker باش يخدم
workers_dev = true

# الربط مع السرفر المحلي أو الخارجي
[vars]
PYTHON_SERVER = "http://127.0.0.1:5000/collect"

# لو تستعمل KV (مستقبلاً)
# [[kv_namespaces]]
# binding = "SAMURAI_STORE"
# id = ""
